import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import dynamic from "next/dynamic";

const Navbar=dynamic(() => import("./_components/Header"),{ssr:false})

const outfit=Outfit({subsets:["latin"]});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
          <Navbar/>
          {children}
          <Toaster />
          <Footer />
      </body>
    </html>
  );
}
